name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build-aquasec-supply-chain
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          security-checks: 'vuln,config,secret'
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          AQUA_URL: "https://api-dev.aquasec.com/v2/build"
          CSPM_URL: "https://stage.api.cloudsploit.com/v2/tokens"


